"""newly updated

Revision ID: 9768fdc57c21
Revises: 8a4f7fcf6154
Create Date: 2025-05-21 22:55:43.027821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9768fdc57c21'
down_revision: Union[str, None] = '8a4f7fcf6154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=1),
               nullable=False)
    op.create_foreign_key(None, 'score', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.alter_column('question', 'is_correct',
               existing_type=sa.String(length=1),
               type_=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
