"""empty message

Revision ID: a95561dd908c
Revises: 6a30ca8cfa79
Create Date: 2025-05-30 21:56:48.638687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95561dd908c'
down_revision: Union[str, None] = '6a30ca8cfa79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', 'expert', name='difficulty'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'difficulty')
    # ### end Alembic commands ###
