"""added expired in status class

Revision ID: e689adbb24f1
Revises: 9768fdc57c21
Create Date: 2025-05-28 22:41:49.368873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e689adbb24f1'
down_revision: Union[str, None] = '9768fdc57c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recent_activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recent_activity',
    sa.Column('activtiy_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', mysql.ENUM('pending', 'Completed'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='recent_activity_ibfk_1'),
    sa.PrimaryKeyConstraint('activtiy_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
